#import "list.typ": *

#let page1 = (
  (
    (tmp.t1,),
    (tmp.t2, tmp.t3, phon.d),
    words.a,
    "Civilization",
    words.of,
    (tmp.t5, phon.say, phon.t),
    pseudo-words.w1,
    sym.bullet,
  ),
  (
    words.they,
    words.built,
    words.a,
    pseudo-words.noun1,
    ",",
    words.and,
    (phon.o, tmp.t11, phon.n),
    words.that,
    pseudo-words.noun1,
    words.they,
    words.built,
  ),
  (
    words.a,
    (tmp.t12, tmp.t2, phon.s),
    sym.bullet,
    words.they,
    words.called,
    words.sacred,
    words.the,
    words.secrets,
    words.of,
  ),
  (
    words.the,
    "Holy Cross,",
    words.and,
    (tmp.t15, tmp.t16, phon.s, tmp.t17, phon.d),
    words.the,
    (phon.p, tmp.t18, tmp.t19),
  ),
  (
    (tmp.t20, tmp.t21),
    words.of,
    (tmp.t22, tmp.t23, tmp.t24, tmp.t25),
    sym.bullet,
    words.they,
    (tmp.t26, phon.n, tmp.t21, phon.d),
    words.to,
    words.the,
    (tmp.t27,),
    (tmp.t28,),
  ),
  (
    words.and,
    (tmp.t29, phon.t),
    pseudo-words.w1,
    (phon.f, tmp.t30, phon.m),
    words.the,
    (phon.s, phon.pay, tmp.t9, phon.z),
    (tmp.t32, phon.t, tmp.t33, phon.n),
    sym.bullet,
  ),
)

#let page2 = (
  (
    (tmp.t34,),
    (tmp.t35,),
    (phon.u, tmp.t36, tmp.t37),
    ",",
    words.an,
    (tmp.t38, tmp.t39, tmp.t40),
    (tmp.t41, phon.d),
    pseudo-words.w1,
    words.was,
    pseudo-words.verb1 + (phon.d,),
    sym.bullet,
  ),
  (
    (tmp.t44, tmp.t45, phon.l, phon.z),
    words.of,
    (tmp.t46, phon.l, phon.f),
    ",",
    (tmp.t15, tmp.t47, phon.d),
    (tmp.t48, tmp.t49, phon.n, phon.z),
    words.of,
    words.the,
    (phon.f, phon.u, tmp.t21),
    ",",
  ),
  (
    words.untombed,
    words.and,
    words.cast,
    words.into,
    (tmp.t52, tmp.t53, tmp.t54, tmp.t55),
    words.and,
    (tmp.t56, tmp.t57),
    sym.bullet,
  ),
  (
    words.a,
    (tmp.t58, tmp.t43),
    words.in,
    words.the,
    (phon.ka, tmp.t59, tmp.t60, tmp.t61, phon.l), // Cathedral ?
    (phon.p, tmp.t18, phon.n),
    words.a,
    (phon.s, tmp.t62, tmp.t63),
    words.of,
  ),
  (
    (phon.po, tmp.t64, phon.n, tmp.t65, phon.l),
    sym.bullet,
    (tmp.t66, tmp.t67, phon.p, phon.s),
    (tmp.t24,), // At ?
    (tmp.t35,),
    words.the,
    (tmp.t68, tmp.t69, phon.l, phon.d),
    (phon.p, tmp.t70, phon.z), // Prize?
    ",",
  ),
  (
    "The Power To Defy Death",
    sym.bullet,
  ),
)

#let page3 = (
  (
    "A Terrible Power Rises",
  ),
  (
    words.the,
    pseudo-words.verb1 + (tmp.t40,),
    "Hero",
    words.opened,
    words.a,
    words.tomb,
    words.and,
    (tmp.t22, tmp.t72, phon.l, phon.d),
  ),
  (
    words.a,
    (tmp.t73, tmp.t74, tmp.t37),
    (phon.t, tmp.t75, tmp.t76),
    sym.bullet,
    words.a,
    "Cathedral",
    words.was,
    words.built,
  ),
  (
    words.to,
    (tmp.t26, tmp.t19, tmp.t78),
    (tmp.t79, phon.s),
    (tmp.t80,),
    (tmp.t81, tmp.t82, phon.in),
    words.of,
    (tmp.t77, phon.f),
    words.and,
    words.the,
  ),
  (
    (tmp.t68, tmp.t76, tmp.t83, phon.l),
    (tmp.t84,),
    (tmp.t5, tmp.t85, phon.n, tmp.t86, phon.d),
    words.the,
    pseudo-words.people + (phon.s,),
    words.of,
    (phon.ho, tmp.t58),
    (tmp.t74, tmp.t2, tmp.t72, tmp.t15),
    sym.bullet,
  ),
)

#let page4 = (
  (
    words.the,
    (tmp.t58, tmp.t43),
    (tmp.t87, tmp.t8, tmp.t84, phon.k, phon.t),
    "!",
    words.the,
    (tmp.t83, phon.l, phon.k, tmp.t30, phon.m),
    (tmp.t88, tmp.t89, phon.d),
    "!",
    words.a,
    words.hole,
    words.in,
  ),
)

#let pages = (
  page1,
  page2,
  page3,
  page4,
)
